### PR TITLE
 Changed resolving Location Services status (closes #327)

### LINKED ISSUE #327: Location Services disabled (code 4) even when Location Services are Activated - Android Pen
**Error:** 
com.polidea.rxandroidble.exceptions.BleScanException: Location Services disabled (code 4)

**Facts:**
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/> is in manifest and user accepts the checkSelfPermission.

**Double checked:**

I double checked it in settings and location services are enabled and the app is allowed to such permission.

**Hardware && versions:**
[ro.build.version.release]: [7.1.2]
[ro.build.version.sdk]: [25]
[ro.product.board]: [q8723bs]
[ro.product.brand]: [Amlogic]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [q8723bs]
[ro.product.firmware]: [00502001]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [Amlogic]
[ro.product.model]: [H96 PRO]
[ro.product.name]: [q8723bs]

Hardware [Link](https://www.geekbuying.com/item/H96-Pro-4K-Amlogic-S912-KODI-17-3-TV-Dongle-382407.html?Currency=USD&gclid=EAIaIQobChMI3rqj3Ind1wIVCD8bCh3E8Qm2EAQYASABEgIlE_D_BwE)

I can't figure out the reason of this exception. Any idea?

### PR DESCRIPTION
**Pull request by dariuszseweryn**
As it turned out it is possible to detect what is the current status of the Location even on devices that are not phones.

### CODE REVIEW

File: rxandroidble/src/main/java/com/polidea/rxandroidble/ClientComponent.java [hunk 1]
```diff
@@ -131,6 +133,19 @@ static int provideDeviceSdk() {
...
         }
 
+        @Provides
+        ContentResolver provideContentResolver() {
+            return context.getContentResolver();
+        }
+
+        @Provides
+        @Named(PlatformConstants.STRING_LOCATION_SERVICES_CHANGED_INTENT_ACTION)
+        static String provideLocationServicesChangedIntentAction() {
```
Comment (uKL) [inline rxandroidble/src/main/java/com/polidea/rxandroidble/ClientComponent.java]: I'm always hesitant when I see this. Is it a dependency or part of the logic? If a dependency then it's a good idea to inject, if a logic then not. 

I think that SDK_INT is a dependency here.

Comment (uKL) [reply rxandroidble/src/main/java/com/polidea/rxandroidble/ClientComponent.java]: Do you know any good patterns to distinguish?

File: rxandroidble/src/main/java/com/polidea/rxandroidble/internal/util/CheckerLocationProvider.java [hunk 2]
```diff
@@ -1,21 +1,32 @@
...
 
+import android.annotation.TargetApi;
+import android.content.ContentResolver;
 import android.location.LocationManager;
 
+import android.os.Build;
+import android.provider.Settings;
 import bleshadow.javax.inject.Inject;
 
+@TargetApi(Build.VERSION_CODES.KITKAT)
```
Comment (uKL) [inline rxandroidble/src/main/java/com/polidea/rxandroidble/internal/util/CheckerLocationProvider.java]: I think it deserves `RequiresApi` as it shouldn't be called on earlier APIs.

File: rxandroidble/src/main/java/com/polidea/rxandroidble/ClientComponent.java [hunk 3]
```diff
@@ -131,6 +138,42 @@ static int provideDeviceSdk() {
...
+
+        @Provides
+        @Named(NamedBooleanObservables.LOCATION_SERVICES_OK)
+        Observable<Boolean> provideLocationServicesOkObservable(
+                @Named(PlatformConstants.INT_DEVICE_SDK) int deviceSdk,
+                Provider<LocationServicesOkObservableApi18> locationServicesOkObservableApi18Provider,
+                Provider<LocationServicesOkObservableApi23> locationServicesOkObservableApi23Provider
+        ) {
+            return deviceSdk < Build.VERSION_CODES.M
+                    ? locationServicesOkObservableApi18Provider.get()
```
Comment (uKL) [inline rxandroidble/src/main/java/com/polidea/rxandroidble/ClientComponent.java]: I believe this is equivalent to `ObservableUtil.justOnNext(true)`
